"""initial tables

Peek Plugin Database Migration Script

Revision ID: c1d2d5475c64
Revises: 
Create Date: 2018-06-21 22:49:45.976813

"""

# revision identifiers, used by Alembic.
revision = 'c1d2d5475c64'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GraphDbModelSet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('propsJson', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name'),
    schema='pl_graphdb'
    )
    op.create_table('Setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_graphdb'
    )
    op.create_table('GraphDbChunkQueue',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_graphdb.GraphDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'chunkKey'),
    schema='pl_graphdb'
    )
    op.create_table('GraphDbSegmentType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_graphdb.GraphDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_graphdb'
    )
    op.create_index('idx_DocType_model_name', 'GraphDbSegmentType', ['modelSetId', 'name'], unique=True, schema='pl_graphdb')
    op.create_index('idx_DocType_model_title', 'GraphDbSegmentType', ['modelSetId', 'title'], unique=True, schema='pl_graphdb')
    op.create_table('GraphDbEncodedChunkTuple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.Column('encodedData', sa.LargeBinary(), nullable=False),
    sa.Column('encodedHash', sa.String(), nullable=False),
    sa.Column('lastUpdate', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_graphdb.GraphDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_graphdb'
    )
    op.create_index('idx_Chunk_modelSetId_chunkKey', 'GraphDbEncodedChunkTuple', ['modelSetId', 'chunkKey'], unique=False, schema='pl_graphdb')
    op.create_table('GraphDbProperty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_graphdb.GraphDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_graphdb'
    )
    op.create_index('idx_GraphDbProp_model_name', 'GraphDbProperty', ['modelSetId', 'name'], unique=True, schema='pl_graphdb')
    op.create_index('idx_GraphDbProp_model_title', 'GraphDbProperty', ['modelSetId', 'title'], unique=True, schema='pl_graphdb')
    op.create_table('SettingProperty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settingId', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.Column('char_value', sa.String(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['settingId'], ['pl_graphdb.Setting.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_graphdb'
    )
    op.create_index('idx_SettingProperty_settingId', 'SettingProperty', ['settingId'], unique=False, schema='pl_graphdb')
    op.create_table('GraphDbSegment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('segmentTypeId', sa.Integer(), nullable=False),
    sa.Column('importGroupHash', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.Column('segmentJson', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['segmentTypeId'], ['pl_graphdb.GraphDbSegmentType.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_graphdb.GraphDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_graphdb'
    )
    op.create_index('idx_Segment_segmentType', 'GraphDbSegment', ['segmentTypeId'], unique=False, schema='pl_graphdb')
    op.create_index('idx_Segment_gridKey', 'GraphDbSegment', ['chunkKey'], unique=False, schema='pl_graphdb')
    op.create_index('idx_Segment_importGroupHash', 'GraphDbSegment', ['importGroupHash'], unique=False, schema='pl_graphdb')
    op.create_index('idx_Segment_key', 'GraphDbSegment', ['modelSetId', 'key'], unique=True, schema='pl_graphdb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_Segment_key', table_name='GraphDbSegment', schema='pl_graphdb')
    op.drop_index('idx_Segment_importGroupHash', table_name='GraphDbSegment', schema='pl_graphdb')
    op.drop_index('idx_Segment_gridKey', table_name='GraphDbSegment', schema='pl_graphdb')
    op.drop_index('idx_Segment_segmentType', table_name='GraphDbSegment', schema='pl_graphdb')
    op.drop_table('GraphDbSegment', schema='pl_graphdb')
    op.drop_index('idx_SettingProperty_settingId', table_name='SettingProperty', schema='pl_graphdb')
    op.drop_table('SettingProperty', schema='pl_graphdb')
    op.drop_index('idx_GraphDbProp_model_title', table_name='GraphDbProperty', schema='pl_graphdb')
    op.drop_index('idx_GraphDbProp_model_name', table_name='GraphDbProperty', schema='pl_graphdb')
    op.drop_table('GraphDbProperty', schema='pl_graphdb')
    op.drop_index('idx_Chunk_modelSetId_chunkKey', table_name='GraphDbEncodedChunkTuple', schema='pl_graphdb')
    op.drop_table('GraphDbEncodedChunkTuple', schema='pl_graphdb')
    op.drop_index('idx_DocType_model_title', table_name='GraphDbSegmentType', schema='pl_graphdb')
    op.drop_index('idx_DocType_model_name', table_name='GraphDbSegmentType', schema='pl_graphdb')
    op.drop_table('GraphDbSegmentType', schema='pl_graphdb')
    op.drop_table('GraphDbChunkQueue', schema='pl_graphdb')
    op.drop_table('Setting', schema='pl_graphdb')
    op.drop_table('GraphDbModelSet', schema='pl_graphdb')
    # ### end Alembic commands ###