"""added key index

Peek Plugin Database Migration Script

Revision ID: c587bfdd97d5
Revises: d7ccfd6a4a93
Create Date: 2018-10-14 16:09:52.974644

"""

# revision identifiers, used by Alembic.
revision = 'c587bfdd97d5'
down_revision = 'd7ccfd6a4a93'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ItemKeyIndexCompilerQueue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_graphdb.GraphDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'chunkKey'),
    schema='pl_graphdb'
    )
    op.create_table('ItemKeyIndexEncodedChunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.Column('encodedData', sa.LargeBinary(), nullable=False),
    sa.Column('encodedHash', sa.String(), nullable=False),
    sa.Column('lastUpdate', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_graphdb.GraphDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_graphdb'
    )
    op.create_index('idx_ItemKeyIndexEnc_modelSetId_chunkKey', 'ItemKeyIndexEncodedChunk', ['modelSetId', 'chunkKey'], unique=False, schema='pl_graphdb')
    op.create_table('ItemKeyType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_graphdb.GraphDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_graphdb'
    )
    op.create_index('idx_DocType_model_key', 'ItemKeyType', ['modelSetId', 'key'], unique=True, schema='pl_graphdb')
    op.create_index('idx_DocType_model_name', 'ItemKeyType', ['modelSetId', 'name'], unique=True, schema='pl_graphdb')
    op.create_table('ItemKeyIndex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('itemKeyTypeId', sa.Integer(), nullable=False),
    sa.Column('importGroupHash', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.Column('packedJson', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['itemKeyTypeId'], ['pl_graphdb.ItemKeyType.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_graphdb.GraphDbModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_graphdb'
    )
    op.create_index('idx_ItemKeyIndex_gridKey', 'ItemKeyIndex', ['chunkKey'], unique=False, schema='pl_graphdb')
    op.create_index('idx_ItemKeyIndex_importGroupHash', 'ItemKeyIndex', ['importGroupHash'], unique=False, schema='pl_graphdb')
    op.create_index('idx_ItemKeyIndex_item_keyType', 'ItemKeyIndex', ['itemKeyTypeId'], unique=False, schema='pl_graphdb')
    op.create_index('idx_ItemKeyIndex_key', 'ItemKeyIndex', ['modelSetId', 'key'], unique=True, schema='pl_graphdb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ItemKeyIndex_key', table_name='ItemKeyIndex', schema='pl_graphdb')
    op.drop_index('idx_ItemKeyIndex_item_keyType', table_name='ItemKeyIndex', schema='pl_graphdb')
    op.drop_index('idx_ItemKeyIndex_importGroupHash', table_name='ItemKeyIndex', schema='pl_graphdb')
    op.drop_index('idx_ItemKeyIndex_gridKey', table_name='ItemKeyIndex', schema='pl_graphdb')
    op.drop_table('ItemKeyIndex', schema='pl_graphdb')
    op.drop_index('idx_DocType_model_name', table_name='ItemKeyType', schema='pl_graphdb')
    op.drop_index('idx_DocType_model_key', table_name='ItemKeyType', schema='pl_graphdb')
    op.drop_table('ItemKeyType', schema='pl_graphdb')
    op.drop_index('idx_ItemKeyIndexEnc_modelSetId_chunkKey', table_name='ItemKeyIndexEncodedChunk', schema='pl_graphdb')
    op.drop_table('ItemKeyIndexEncodedChunk', schema='pl_graphdb')
    op.drop_table('ItemKeyIndexCompilerQueue', schema='pl_graphdb')
    # ### end Alembic commands ###